# Generated by Django 5.1.1 on 2024-11-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewise', '0007_rename_user_id_userhousewise_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhousewise',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userhousewise',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
