# Generated by Django 5.1.1 on 2024-11-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewise', '0008_userhousewise_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhousewise',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
