# Generated by Django 5.1.1 on 2024-11-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housewise', '0008_userhousewise_is_staff_alter_userhousewise_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhousewise',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userhousewise',
            name='is_superuser',
        ),
    ]
