# Generated by Django 5.1.1 on 2024-11-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewise', '0010_userhousewise_is_active_userhousewise_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhousewise',
            name='profile_icon',
            field=models.CharField(blank=True, default='default_icon.png', max_length=255, null=True),
        ),
    ]
