# Generated by Django 5.1.1 on 2024-12-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewise', '0011_userhousewise_profile_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
