# Generated by Django 5.1.1 on 2024-12-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housewise', '0012_project_is_published_project_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cost',
        ),
    ]
