# Generated by Django 5.1.1 on 2024-12-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewise', '0015_alter_rooms_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_number',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
