# Generated by Django 5.1.1 on 2024-12-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewise', '0016_alter_rooms_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='active_button',
            field=models.CharField(choices=[('TopStart', 'TopStart'), ('TopEnd', 'TopEnd'), ('BottomStart', 'BottomStart'), ('BottomEnd', 'BottomEnd')], default='TopStart', max_length=20),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_number',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=1),
        ),
    ]
