# Generated by Django 5.1.1 on 2024-12-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('housewise', '0017_rooms_active_button_alter_rooms_room_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='likes',
        ),
    ]
