# Generated by Django 5.1.1 on 2024-12-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housewise', '0021_alter_userhousewise_profile_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhousewise',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
